import Head from 'next/head'
import MainTitle from "@/components/MainTitle";
import FromWhom from "@/components/FromWhom";
import ThematicSection from "@/components/ThematicSection";
import ForParticipants from "@/components/ForParticipants";
import PavilionInfo from "@/components/PavilionInfo";
import HowToGetTo from "@/components/HowToGetTo";
import Advertising from "@/components/Advertising";
import FormSubscribe from "@/components/FormSubscribe/FormSubscribe";
import Modal from "@/components/Modal/Modal";
import {useState} from "react";

export default function Home() {
    const [modalStatus, setModalStatus] = useState(false)
    const handleModal = (status: boolean)=>{
        setModalStatus(status)
    }
  return (
    <>
      <Head>
        <title>Здоровье-EXPO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <MainTitle/>
          <FromWhom/>
          <ThematicSection/>
          <ForParticipants handleModal={handleModal}/>
          <PavilionInfo/>
          <Advertising handleModal={handleModal}/>
          <HowToGetTo title={'Место проведения'}/>
          <Modal setModalStatus={setModalStatus} modalStatus={modalStatus}>
              <FormSubscribe handleStatus={handleModal}/>
          </Modal>
      </main>
    </>
  )
}
